### ISSUE TITLE
cannot build / npm install MacOS 10.14.1

### ISSUE THREAD

**Issue by spencercap** [2bbb/node-abletonlink#9]
hi, i used this rad little library a while back, but now cannot build or npm install with any success. simply cloning the repo and running `npm i` i get many errors including:
```
note: 
      'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., asy...
```

i also tried the [example repo](https://github.com/2bbb/node-abletonlink-example) and it appears to have failed at the `autogypi && node-gyp rebuild` stage

my system:
```
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abletonlink@0.0.3 build: `autogypi && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abletonlink@0.0.3 build script.
```

ALSO, i am using MacOS 10.14.1, could this be the issue?

**Comment by spencercap** [comment]
@2bbb thanks so much! let me know if you want to run tests on my end.

**Comment by 2bbb** [comment]
@spencercap 
if it's ok, please give me 

* full log of `npm i abletonlink`
* `clang++ --version`
* `python --version`

thanks.

**Comment by spencercap** [comment]
`clang++ --version`:
```
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

`python --version`:
```
Python 2.7.10
```


`npm i abletonlink` in my old project that includes v0.0.3:
```
> abletonlink@0.0.3 install /Users/Spencer/Documents/github/node-abletonlink-2servers/node_modules/abletonlink
> npm run build


> abletonlink@0.0.3 build /Users/Spencer/Documents/github/node-abletonlink-2servers/node_modules/abletonlink
> autogypi && node-gyp rebuild

  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/src/nbind.o
In file included from ../src/nbind.cc:1:
In file included from ../src/./node-abletonlink.hpp:7:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
../../nan/nan.h:1081:96: error: too many arguments to function call, expected at most 4, have
      5
  ...= string->WriteUtf8(v8::Isolate::GetCurrent(), str_, static_cast<int>(len), 0, flags);
       ~~~~~~~~~~~~~~~~~                                                            ^~~~~
/Users/Spencer/.node-gyp/10.8.0/include/node/v8.h:2622:3: note: 'WriteUtf8' declared here
  int WriteUtf8(char* buffer,
  ^
1 error generated.
make: *** [Release/obj.target/nbind/src/nbind.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Spencer/Documents/github/node-abletonlink-2servers/node_modules/abletonlink
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abletonlink@0.0.3 build: `autogypi && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abletonlink@0.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Spencer/.npm/_logs/2018-12-17T06_07_19_100Z-debug.log
npm WARN node-abletonlink-example@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abletonlink@0.0.3 install: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abletonlink@0.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Spencer/.npm/_logs/2018-12-17T06_07_19_765Z-debug.log
```


`npm i` within [this main repo](https://github.com/2bbb/node-abletonlink) (currently v0.0.7):
```
> abletonlink@0.0.7 install /Users/Spencer/Downloads/node-abletonlink-master
> npm run build


> abletonlink@0.0.7 build /Users/Spencer/Downloads/node-abletonlink-master
> npm config set msvs_version 2015 && autogypi && node-gyp rebuild

  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/src/nbind.o
In file included from ../src/nbind.cc:1:
../src/./node-abletonlink.hpp:11:10: fatal error: 'ableton/Link.hpp' file not found
#include <ableton/Link.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/nbind/src/nbind.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Spencer/Downloads/node-abletonlink-master
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abletonlink@0.0.7 build: `npm config set msvs_version 2015 && autogypi && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abletonlink@0.0.7 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Spencer/.npm/_logs/2018-12-17T06_09_54_838Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abletonlink@0.0.7 install: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abletonlink@0.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Spencer/.npm/_logs/2018-12-17T06_09_54_888Z-debug.log
```


`npm i` within [the example repo](https://github.com/2bbb/node-abletonlink-example) which also uses abletonlink v0.0.3:
```
> abletonlink@0.0.3 install /Users/Spencer/Downloads/node-abletonlink-example-master/node_modules/abletonlink
> npm run build


> abletonlink@0.0.3 build /Users/Spencer/Downloads/node-abletonlink-example-master/node_modules/abletonlink
> autogypi && node-gyp rebuild

  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/src/nbind.o
In file included from ../src/nbind.cc:1:
In file included from ../src/./node-abletonlink.hpp:7:
In file included from ../node_modules/nbind/include/nbind/nbind.h:8:
In file included from ../node_modules/nbind/include/nbind/noconflict.h:8:
In file included from ../node_modules/nbind/include/nbind/BindDefiner.h:11:
In file included from ../node_modules/nbind/include/nbind/api.h:71:
In file included from ../node_modules/nbind/include/nbind/v8/BindWrapper.h:55:
In file included from ../node_modules/nan/nan.h:192:
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in
      'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/nbind.cc:1:
In file included from ../src/./node-abletonlink.hpp:7:
In file included from ../node_modules/nbind/include/nbind/nbind.h:8:
In file included from ../node_modules/nbind/include/nbind/noconflict.h:8:
In file included from ../node_modules/nbind/include/nbind/BindDefiner.h:11:
In file included from ../node_modules/nbind/include/nbind/api.h:71:
In file included from ../node_modules/nbind/include/nbind/v8/BindWrapper.h:55:
../node_modules/nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use
      MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/Spencer/.node-gyp/10.8.0/include/node/node.h:171:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/Spencer/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/nbind.cc:1:
In file included from ../src/./node-abletonlink.hpp:7:
In file included from ../node_modules/nbind/include/nbind/nbind.h:8:
In file included from ../node_modules/nbind/include/nbind/noconflict.h:8:
In file included from ../node_modules/nbind/include/nbind/BindDefiner.h:11:
In file included from ../node_modules/nbind/include/nbind/api.h:71:
In file included from ../node_modules/nbind/include/nbind/v8/BindWrapper.h:55:
../node_modules/nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use
      MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/Spencer/.node-gyp/10.8.0/include/node/node.h:164:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/Spencer/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/nbind.cc:1:
In file included from ../src/./node-abletonlink.hpp:7:
In file included from ../node_modules/nbind/include/nbind/nbind.h:8:
In file included from ../node_modules/nbind/include/nbind/noconflict.h:8:
In file included from ../node_modules/nbind/include/nbind/BindDefiner.h:11:
In file included from ../node_modules/nbind/include/nbind/api.h:71:
In file included from ../node_modules/nbind/include/nbind/v8/BindWrapper.h:55:
../node_modules/nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use
      MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/Spencer/.node-gyp/10.8.0/include/node/node.h:157:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/Spencer/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/nbind.cc:1:
In file included from ../src/./node-abletonlink.hpp:7:
In file included from ../node_modules/nbind/include/nbind/nbind.h:8:
In file included from ../node_modules/nbind/include/nbind/noconflict.h:8:
In file included from ../node_modules/nbind/include/nbind/BindDefiner.h:11:
In file included from ../node_modules/nbind/include/nbind/api.h:71:
In file included from ../node_modules/nbind/include/nbind/v8/BindWrapper.h:55:
../node_modules/nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use
      MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/Spencer/.node-gyp/10.8.0/include/node/node.h:171:1: note: 'MakeCallback' has been
      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/Spencer/.node-gyp/10.8.0/include/node/node.h:88:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/nbind/src/nbind.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Spencer/Downloads/node-abletonlink-example-master/node_modules/abletonlink
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abletonlink@0.0.3 build: `autogypi && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abletonlink@0.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Spencer/.npm/_logs/2018-12-17T06_11_27_770Z-debug.log
npm WARN node-abletonlink-example@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abletonlink@0.0.3 install: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abletonlink@0.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Spencer/.npm/_logs/2018-12-17T06_11_28_499Z-debug.log
```


`npm i abletonlink` in a blank directory:
```
> abletonlink@0.0.7 install /Users/Spencer/Desktop/test/node_modules/abletonlink
> npm run build


> abletonlink@0.0.7 build /Users/Spencer/Desktop/test/node_modules/abletonlink
> npm config set msvs_version 2015 && autogypi && node-gyp rebuild

  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/src/nbind.o
In file included from ../src/nbind.cc:1:
In file included from ../src/./node-abletonlink.hpp:13:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:71:
In file included from ../../nbind/include/nbind/v8/BindWrapper.h:55:
../../nan/nan.h:1081:96: error: too many arguments to function call, expected at
      most 4, have 5
  ...string->WriteUtf8(v8::Isolate::GetCurrent(), str_, static_cast<int>(len), 0, flags);
     ~~~~~~~~~~~~~~~~~                                                            ^~~~~
/Users/Spencer/.node-gyp/10.8.0/include/node/v8.h:2622:3: note: 'WriteUtf8'
      declared here
  int WriteUtf8(char* buffer,
  ^
1 error generated.
make: *** [Release/obj.target/nbind/src/nbind.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Spencer/Desktop/test/node_modules/abletonlink
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abletonlink@0.0.7 build: `npm config set msvs_version 2015 && autogypi && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abletonlink@0.0.7 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Spencer/.npm/_logs/2018-12-17T06_12_56_494Z-debug.log
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abletonlink@0.0.7 install: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abletonlink@0.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Spencer/.npm/_logs/2018-12-17T06_12_57_042Z-debug.log
```

**Comment by 2bbb** [comment]
@spencercap 

hmmmmm...
I installed macOS Mojave 10.14.2 into external SSD, and test it.

```
$ python --version
Python 2.7.10
$ node -v
v10.8.0
$ clang++ --version
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

but I installed abletonlink@0.0.7 and abletonlink@0.0.3 with no problem.
this is a mystery...

**Comment by 2bbb** [comment]
if you feel this thread is needed, feel free to re-open.
